name: PSC Spack CI

on:
  push:
    branches: [ main, 'pr/*' ]
  pull_request:
    branches: [ main ]

jobs:
  spack-psc:
    runs-on: ubuntu-latest
    container: ghcr.io/psc-code/psc-spack-ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: dev-build psc +tests
      run: |
        . /opt/spack/share/spack/setup-env.sh
        spack dev-build psc@local +tests

  spack-psc-cuda:
    runs-on: ubuntu-latest
    container: ghcr.io/psc-code/psc-spack-cuda-ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: dev-build psc +tests +cuda
      run: |
        . /opt/spack/share/spack/setup-env.sh
        spack dev-build psc@local +tests +cuda

  # spack-psc-cuda-rmm:
  #   runs-on: ubuntu-latest
  #   container: ghcr.io/psc-code/psc-spack-cuda-ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: dev-build psc +tests +cuda +rmm
  #     run: |
  #       . /opt/spack/share/spack/setup-env.sh
  #       spack dev-build psc@local +tests +cuda +rmm
