name: PSC CI

on:
  push:
    branches: [ main, 'pr/*' ]
  pull_request:
    branches: [ main ]

jobs:
  tests-cpu:
    runs-on: ubuntu-latest
    container: ghcr.io/psc-code/psc-cpp-ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
    - name: build
      run: cmake --build build
    - name: test
      run: cmake --build build -t test

  tests-spack-cpu:
    runs-on: ubuntu-latest
    container: ghcr.io/psc-code/psc-spack-ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
    - name: build
      run: cmake --build build
    - name: test
      run: cmake --build build -t test

  build-spack-cuda:
    runs-on: ubuntu-latest
    container: ghcr.io/psc-code/psc-spack-cuda-ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        #. /opt/spack/share/spack/setup-env.sh
        #spack repo list
        #spack env activate /root/psc-env
        export CMAKE_PREFIX_PATH=/root/psc-env/.spack-env/view
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_CUDA=ON -G Ninja
    - name: build
      run: cmake --build build
